### ISSUE TITLE
Composer install issue

### ISSUE THREAD

**Issue by luki922** [loic-sharma/Anvil#2]
When i use: composer install i got this error:

[RuntimeException]  
  Failed to clone http://github.com/loic-sharma/menu.git, git was not found,  
  check that it is installed and in your PATH env.                             

  sh: 1: git: not found

**Comment by loic-sharma** [comment]
That's strange. I'll look at this when I get back home.

**Comment by loic-sharma** [comment]
It looks like you don't have git installed on your computer, or if you do, you don't have it in your PATH variable. Try just running `git` on the terminal line.

**Comment by luki922** [comment]
ohh thank you. I completely forgot about it :/ Now everything works :)

**Comment by loic-sharma** [comment]
Awesome! Feel free to open another issue if you need anything else.
