### ISSUE TITLE
Installer Step-2 error and Admin Panel

### ISSUE THREAD

**Issue by luki922** [loic-sharma/Anvil#3]
1. In step-2 have error:

BadMethodCallException
Method [validateRoot] does not exist.

But when change this (in routes.php): 
'password' => array(''),  for this 'password' => array('required'), all works :)
1. Error when i go to Admin Panel from link:

Exception
Call to undefined method [addAsset].
Open: /var/www/anvil/anvil/classes/Anvil/Plugins/Plugin.php
                    return call_user_func_array(array($model, $method), $args);
            }
        }

```
    else
    {
        // The plugin has no model, throw an exception.
        throw new \Exception("Call to undefined method [$method].");
    }
}
```

**Comment by loic-sharma** [comment]
Thanks for reporting! The installer is still a huge mess, I just threw together something that worked really fast a while back. Once I'm done polishing Anvil, I'll rewrite the installer! :)

**Comment by luki922** [comment]
No problem :) For this moment installer is good fast and stable :) but why i cant go to admin panel after installation? :p

Exception
Call to undefined method [addAsset].
Open: /var/www/anvil/anvil/classes/Anvil/Plugins/Plugin.php
return call_user_func_array(array($model, $method), $args);
}
}

```
else
{
    // The plugin has no model, throw an exception.
    throw new \Exception("Call to undefined method [$method].");
}
```

}

**Comment by loic-sharma** [comment]
Anvil had a working admin panel a while back, but I never really liked it. I toyed with the idea of an admin panel like [MojoMotor's](http://ellislab.com/mojomotor), but I didn't like that either. I still haven't decided really how I want to build the admin panel.

But anyways, I haven't updated the admin panel in ages. So it's using a lot of outdated classes that I removed. I can start updating it if you want.

**Comment by luki922** [comment]
I always have this same problem when I build app :p if you can update would be grateful and we can working on a project :)

**Comment by loic-sharma** [comment]
Admin panel should work now. The navigation bar is empty for some reason (I don't think the navigation links are added yet in the installer), but you can access the admin panel for a module at `admin/<module name>`. So for example, the `Blog` module would be: `admin/blog`.

**Comment by loic-sharma** [comment]
Lots of the admin pages are currently broken. I'll work on fixing them up and making sure the installer correctly adds the navigation links tomorrow.

**Comment by luki922** [comment]
thanks for update. Now I will download, install and check all :) Anvil its really good cms, there all is a module :) Ok i will waiting for it :)
